cmake -S ./TP1_code -B ./TP1_code/build \
	-DCMAKE_BUILD_TYPE=Debug \
	-DGLFW_BUILD_EXAMPLES=OFF \
	-DGLFW_BUILD_TESTS=OFF \
	-DGLFW_BUILD_DOCS=OFF \
	-DGLFW_INSTALL=OFF \
	-DRMLUI_PRECOMPILED_HEADERS=OFF \
	-DBUILD_TESTING=OFF